### ISSUE TITLE
Slayer / Choppa Career

### ISSUE THREAD

**Issue by Neil0r** [dalen/RoRBuilder#13]
The listet damage values of corresponding skills are completely different. For example: 

Slasha: 202 dmg vs. Pulverizing Strike 191 dmg
Lotsa Choppin: 102-142 dmg vs. Flurry 63-73 dmg

I don't think that's ok?

**Comment by dalen** [comment]
I updated the damage values on those skills. Slasha & Pulverizing Strike 191 dmg both do 191 at lvl 40. Lotsa Choppin & Flurry seem to do different damage though oddly enough.
