### ISSUE TITLE
Witch Elf Issues

### ISSUE THREAD

**Issue by enshoe** [dalen/RoRBuilder#14]
Hi,
There is a few WE issues I have found:
- Mark of Morathi tactic missing
- Frenzied Mayhem tactic description is wrong
- Sacrificial Stab has an error in the description. The buff increases auto attack damage, not speed.
- Sacrificial Stab positional requirement is not present ingame.
- Heart Seeker description typo "Knocksdown your target" -> "Knocks down your target"

**Comment by dalen** [comment]
Thanks for the report. Pushing fixes for all of these issues now.

**Comment by enshoe** [comment]
Great work!
