### ISSUE TITLE
Shared links are not working consistently

### ISSUE THREAD

**Issue by ChrisRBe** [dalen/RoRBuilder#207]
Hey @dalen,
I created a build on the website, clicked share, copied the link and try to open it in the same browser.

Result: Build is not opened
Expected: Build is opened

Tested with URL:
https://builder.returnofreckoning.com/career/archmage/s?l=40&r=70&tl=4&mp=0&pA=13&pB=0&pC=9&m1=3445&m2=3448&m3=3449&m4=3450&ma=3459,3455,3457,3471&mm=&mt=6103,3458,3456&t=3432,3437,3458,3431

**Comment by dalen** [comment]
Thanks for the report. It was an issue in one of the number conversions. I pushed a fix that should be live soon.
