### ISSUE TITLE
[Career Builder] Unshakable Focus morale for Squig Herders

### ISSUE THREAD

**Issue by SilverWF** [dalen/RoRBuilder#227]
The Career Builder shows, that Squig Herder has morale 2 Unshakable Focus, while in fact, they didn't have it for long ago
Please fix

![img-2019-11-24-16-46-00](https://user-images.githubusercontent.com/16439840/69496451-5e427480-0ee3-11ea-9cd3-6d251ddbc26e.png)

**Comment by dalen** [comment]
Thanks for the report, I pushed a fix now.
