### ISSUE TITLE
[KOTBS] All tactics are displayed in the list as core tactics

### ISSUE THREAD

**Issue by zulnam** [dalen/RoRBuilder#289]
Expected: 
When a mastery tactic is unlocked, it should then be placed to the poll of available tactics.

Actual:
All mastery tactics are already present in the poll and can be freely selected as if they are unlocked.

Page: https://builder.returnofreckoning.com/career/knight-of-the-blazing-sun
Browser: Chrome (Mac OS)

**Comment by dalen** [comment]
Thanks for report, fixed

**Comment by zulnam** [comment]
No worries man. I really appreciate your website. Use it weekly. Done in ReactJS too! 👍 👍
