### ISSUE TITLE
[WP] Soulfire should say "Requires Great Weapon"

### ISSUE THREAD

**Issue by Rydiak** [dalen/RoRBuilder#8]
As the title says. Soulfire in the WP Wrath tree requires a Great Weapon to use.

**Comment by dalen** [comment]
Thanks for the report, just fixed. Will take a look at the other issue this evening.

**Comment by Rydiak** [comment]
You are very welcome! I've noticed some spelling mistakes on other
abilities too, but wasn't sure if you'd like me to bug report those. I'd be
happy to provide minor editing services to the website if you'd allow me
to. Thanks!

**Comment by dalen** [comment]
You can create a pull request if you are familiar with the Github workflow. But essentially you can go here: https://github.com/Natherul/RoRBuilder/blob/master/public/json/abilities/warrior-priest.json and click edit file and use the web browser editor to edit them. Then at the bottom it will ask you to describe the changes and create a pull request that I can then merge.

**Comment by Rydiak** [comment]
Oh fantastic. Thank you for that info!
