### ISSUE TITLE
Incorrect calculation for maximum number of tactics

### ISSUE THREAD

**Issue by ghost** [dalen/RoRBuilder#810]
https://github.com/dalen/RoRBuilder/blob/master/src/actions/actionTacticLimit.ts

Currently the tactic limits on the career builder are:

Level <= 10: 4 tactics (set by having "limit" default to 4)
Level 10 - 19: 1 tactic
Level 20 - 29: 2 tactics
Level 30 - 39:  3 tactics
Level 40: 4 tactics

This doesn't match what is used in game, which I believe (99% sure!) is currently:

Level <= 8: 0 tactics
Level 8 - 15: 1 tactic
Level 16 - 23: 2 tactics
Level 24 - 31: 3 tactics
Level >= 32: 4 tactics

**Comment by zulnam** [comment]
@dalen if you can confirm this I can look into fixing it
