### ISSUE TITLE
[WP] Sigmar's Shield description

### ISSUE THREAD

**Issue by Rydiak** [dalen/RoRBuilder#9]
Sigmar's Shield lasts for 10 seconds, not 20 seconds as the builder text states.  It also drains 10 Righteous Fury every time the friendly target is hit, instead of 15 Righteous Fury a second.

**Comment by dalen** [comment]
Fixed this as well.

Also btw, thanks for the great Grace WP guide :)

**Comment by Rydiak** [comment]
You are very welcome! Slight correction though. It is 10 RF *per hit*, not
per second.

**Comment by dalen** [comment]
Fixed the RF requirement now.
